/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhom11.iotapp.mainframe;

import com.nhom11.iotapp.event.EventMainFrame;
import com.nhom11.iotapp.event.PublicEvent;
import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;


/**
 *
 * @author Administrator
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        initEvent();
    }
    public void initEvent(){
        PublicEvent.getInstance().setEventMainFrame(new EventMainFrame(){
            @Override
            public void dragingFrame(int x, int y, MouseEvent e) {
                setLocation(e.getXOnScreen() - x,e.getYOnScreen() - y);
                
            }

            @Override
            public void tabBarFrame() {
                setExtendedState(JFrame.ICONIFIED);
            }

            @Override
            public void closeFrame() {
                System.exit(0);
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder = new com.nhom11.iotapp.components.PanelBorder();
        menuForm = new com.nhom11.iotapp.form.MenuForm();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panelBorder.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder.setPreferredSize(new java.awt.Dimension(900, 600));
        panelBorder.setLayout(new java.awt.CardLayout());
        panelBorder.add(menuForm, "card2");

        getContentPane().add(panelBorder, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nhom11.iotapp.form.MenuForm menuForm;
    private com.nhom11.iotapp.components.PanelBorder panelBorder;
    // End of variables declaration//GEN-END:variables
}
