/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.iotapp.components;

import com.nhom11.iotapp.callback.Invokelater;
import com.nhom11.iotapp.enums.PopupType;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author DELL
 */
public class PopupPanel extends javax.swing.JPanel {

    /**
     * Creates new form PopupPanel
     */
    public PopupPanel(String title,String msg,String instruc,PopupType type,Invokelater cancelBtnInvokelater,Invokelater okBtnInvokelater) {
        initComponents();
        lbTitle.setText(title);
        lbmsg.setText(msg);
        lbInstruction.setText(instruc);
        if(cancelBtnInvokelater == null){
            cancleBtn.setVisible(false);
        }
        else {
            cancleBtn.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    cancelBtnInvokelater.call(e);
                }
            
            });
        }
        if(okBtnInvokelater == null){
            okBtn.setVisible(false);
        }
        else{
            okBtn.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e) {
                    okBtnInvokelater.call(e);
                }
            
            });
        }
        if(type == PopupType.SUCCESS){
            imIcon.setImage(new ImageIcon(getClass().getResource("../resources/icon/success.png")));
        }
        else if(type == PopupType.INFO){
            imIcon.setImage(new ImageIcon(getClass().getResource("../resources/icon/infor.png")));
        }
        else {
            imIcon.setImage(new ImageIcon(getClass().getResource("../resources/icon/warning.png")));
        }
    }

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D)g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imIcon = new com.nhom11.iotapp.components.ImagePanel();
        lbTitle = new javax.swing.JLabel();
        lbmsg = new javax.swing.JLabel();
        okBtn = new com.nhom11.iotapp.components.BtnClickAnimate();
        cancleBtn = new com.nhom11.iotapp.components.BtnClickAnimate();
        lbInstruction = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        imIcon.setFit(true);
        imIcon.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/nhom11/iotapp/resources/icon/success.png"))); // NOI18N

        javax.swing.GroupLayout imIconLayout = new javax.swing.GroupLayout(imIcon);
        imIcon.setLayout(imIconLayout);
        imIconLayout.setHorizontalGroup(
            imIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        imIconLayout.setVerticalGroup(
            imIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitle.setText("Title");

        lbmsg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbmsg.setText("Message");

        okBtn.setBackground(new java.awt.Color(102, 204, 0));
        okBtn.setForeground(new java.awt.Color(255, 255, 255));
        okBtn.setText("OK");
        okBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        cancleBtn.setBackground(new java.awt.Color(255, 51, 51));
        cancleBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancleBtn.setText("Cancle");
        cancleBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lbInstruction.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(cancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(imIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInstruction)
                    .addComponent(lbTitle)
                    .addComponent(lbmsg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbmsg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInstruction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nhom11.iotapp.components.BtnClickAnimate cancleBtn;
    private com.nhom11.iotapp.components.ImagePanel imIcon;
    private javax.swing.JLabel lbInstruction;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbmsg;
    private com.nhom11.iotapp.components.BtnClickAnimate okBtn;
    // End of variables declaration//GEN-END:variables
}
