/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom11.iotapp.form;

import com.nhom11.iotapp.bluetooth.BluetoothManager;
import com.nhom11.iotapp.bluetooth.VirtualDevice;
import com.nhom11.iotapp.components.LoadingPanel;
import com.nhom11.iotapp.event.PublicEvent;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class DeviceDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form DeviceDetailForm
     */
    public DeviceDetailForm() {
        initComponents();
        disconBtn.setBackground(Color.white);

        initData();
    }

    public void initData(){
        VirtualDevice device = BluetoothManager.getInstance().getVirtualDevice();
        if(device != null){
            tfId.setText(device.getId());
            tfName.setText(device.getName());
            tfMode.setText("Bluetooth");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.nhom11.iotapp.components.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imagePanel1 = new com.nhom11.iotapp.components.ImagePanel();
        jLabel4 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfMode = new javax.swing.JTextField();
        disconBtn = new com.nhom11.iotapp.components.MyButton();
        updateBtn = new com.nhom11.iotapp.components.MyButton();
        jLabel3 = new javax.swing.JLabel();
        mesureBtn = new com.nhom11.iotapp.components.BtnClickAnimate();

        setBackground(new java.awt.Color(255, 255, 255));

        panelBorder1.setBackground(new java.awt.Color(51, 182, 252));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Device Id:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Device Name:");

        imagePanel1.setFit(true);
        imagePanel1.setImage(new javax.swing.ImageIcon(getClass().getResource("/icon/esp32.png"))); // NOI18N

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Connection Mode: ");

        tfId.setEditable(false);
        tfId.setBackground(new java.awt.Color(51, 182, 252));
        tfId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfId.setForeground(new java.awt.Color(255, 255, 255));
        tfId.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfId.setText("laksdjflkasjdlfjals");
        tfId.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        tfId.setFocusable(false);
        tfId.setOpaque(true);
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        tfName.setEditable(false);
        tfName.setBackground(new java.awt.Color(51, 182, 252));
        tfName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 255, 255));
        tfName.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfName.setText("laksdjflkasjdlfjals");
        tfName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        tfName.setFocusable(false);
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfMode.setEditable(false);
        tfMode.setBackground(new java.awt.Color(51, 182, 252));
        tfMode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfMode.setForeground(new java.awt.Color(255, 255, 255));
        tfMode.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tfMode.setText("laksdjflkasjdlfjals");
        tfMode.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        tfMode.setFocusable(false);
        tfMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfModeActionPerformed(evt);
            }
        });

        disconBtn.setText("Disconnect");
        disconBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        disconBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 71, 121));
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update Info");
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(79, 79, 79)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                        .addComponent(disconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addContainerGap(37, Short.MAX_VALUE)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disconBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Devices Detail");

        mesureBtn.setBackground(new java.awt.Color(51, 182, 252));
        mesureBtn.setForeground(new java.awt.Color(255, 255, 255));
        mesureBtn.setText("Mesure");
        mesureBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mesureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesureBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mesureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(mesureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfModeActionPerformed

    private void disconBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconBtnActionPerformed
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    // TODO add your handling code here:
                    PublicEvent.getInstance().getEventMenuForm().changeForm(new LoadingPanel());
                    BluetoothManager.getInstance().getVirtualDevice().disconnect();
                } catch (IOException ex) {
                    Logger.getLogger(DeviceDetailForm.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    ex.printStackTrace();  } 
            }
        }, "Disconnect Thread").start();
    }//GEN-LAST:event_disconBtnActionPerformed

    private void mesureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesureBtnActionPerformed
        // TODO add your handling code here:
        new Thread(() -> {
            try {
                BluetoothManager.getInstance().getVirtualDevice().mesure();
            } catch (IOException ex) {
                Logger.getLogger(DeviceDetailForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        },"Mesure Thread").start();
    }//GEN-LAST:event_mesureBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nhom11.iotapp.components.MyButton disconBtn;
    private com.nhom11.iotapp.components.ImagePanel imagePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.nhom11.iotapp.components.BtnClickAnimate mesureBtn;
    private com.nhom11.iotapp.components.PanelBorder panelBorder1;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfMode;
    private javax.swing.JTextField tfName;
    private com.nhom11.iotapp.components.MyButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
